server:
  port: 8080
spring:
  jackson:
    default-property-inclusion: NON_EMPTY
    date-format: yyyy-MM-dd HH:mm:ss   # 只对Date类型有效果，因为该配置是用来创建 SimpleDateFormat 的
  mvc:
    # 非json请求反序化日期时的格式
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/dome?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
      username: root
      password: 1234

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  type-enums-package: com.jlee.demo.domain
#result:
#  enabled-http-status: true
#  message-head-title: message

